### ISSUE TITLE
ValueError: unsupported pickle protocol: 181

### ISSUE THREAD

**Issue by Extraltodeus** [lopho/pickle_inspector#2]
Hello, while scanning a model resulting from a custom merge I got the following error :

```
Copyright (C) 2022 Lopho <[contact@lopho.org](mailto:contact@lopho.org)> | Licensed under AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Using preset: stable_diffusion_v1
Scanning file(s): ['/content/drive/MyDrive/AI_MODELS/AshOmeletteWithBurnedPepper.ckpt']
Using white list: ['pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint', 'numpy.core.multiarray.scalar', 'torch.IntStorage', '_codecs.encode', 'torch.FloatStorage', 'torch.HalfStorage', 'torch._utils._rebuild_tensor_v2', 'torch.LongStorage', 'collections.OrderedDict', 'numpy.dtype']
Reading /content/drive/MyDrive/AI_MODELS/AshOmeletteWithBurnedPepper.ckpt
Found pickle in zip: archive/data.pkl
Found pickle in zip: archive/data/244
Scanning: archive/data.pkl
found: torch._utils._rebuild_tensor_v2
found: torch.FloatStorage
found: collections.OrderedDict
Scanning: archive/data/244
Traceback (most recent call last):
  File "scan_pickle.py", line 144, in <module>
    sys.exit(main(sys.argv[1:]).value)
  File "scan_pickle.py", line 136, in main
    result = scan(p, stubPickle)
  File "scan_pickle.py", line 57, in scan
    pickle_module.Unpickler(data[k]).load()
  File "/content/pickle_inspector/pickle_inspector/_pickle_inspector.py", line 134, in load
    result.structure = super().load()
ValueError: unsupported pickle protocol: 181
```

[link to the model](https://drive.google.com/file/d/104uzkTsYurYU2anJq9Mu9SppcJrsXt9I/view?usp=sharing) if you want to test by yourself.

Best Regards

**Comment by lopho** [comment]
Thanks for the report, I'll take a look.

**Comment by lopho** [comment]
Checking if files are pickles is more robust now, checking for invalid pickle protocol versions (e.g. pickle protocol > 5).

@Extraltodeus Your file should be scannable now.

**Comment by Extraltodeus** [comment]
Thanks! Did you try on the file itself by the way?
